apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fritz-exporter
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: fritz-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
