apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fritz-exporter
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: monitoring-fritz-prod
  endpoints:
    - port: "9787"
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
