apiVersion: v1
kind: ConfigMap
metadata:
  name: json-exporter-config
data:
  config.yaml: |
    modules:
      jellyfin:
        headers:
          Authorization: "MediaBrowser Token=$(API_TOKEN)"
          Content-Type: "application/json"
          accept: "application/json"

        body:
          content: '{"CustomQueryString": "SELECT unixepoch(DATETIME(DateCreated, \"+\" || PlayDuration || \" seconds\")) AS Timestamp, UserId, ItemType, ItemName, PlaybackMethod, ClientName, DeviceName, PlayDuration, TRUE AS IsActive FROM PlaybackActivity WHERE DATETIME(DateCreated, \"+\" || PlayDuration || \" seconds\") >= DATETIME(\"now\", \"localtime\", \"-60 seconds\")", "ReplaceUserId": true}'

        metrics:
        - name: jellyfin
          type: object
          help: User playback metrics from Jellyfin
          path: '{ .results[*] }'
          epochTimestamp: '{ [0] }'
          labels:
            user_name: '{ [1] }'
            item_type: '{ [2] }'
            item_name: '{ [3] }'
            playback_method: '{ [4] }'
            client_name: '{ [5] }'
            device_name: '{ [6] }'
          values:
            play_duration: '{ [7] }'