apiVersion: v1
kind: Service
metadata:
  name: prometheus-json-exporter
spec:
  selector:
    app: prometheus-json-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 7979
      targetPort: 7979