apiVersion: v1
kind: Service
metadata:
  name: prometheus-json-exporter
  namespace: monitoring
spec:
  selector:
    app: prometheus-json-exporter
  ports:
    - protocol: TCP
      port: 7979
      targetPort: 7979