qbittorrent:
  persistence:
    config:
      enabled: true
      storageClass: "longhorn"
    downloads:
      enabled: true
      mountPath: /downloads
      type: pvc
      existingClaim: downloads-pvc