apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-pv
spec:
  capacity:
    storage: 10Gi # This is a placeholder, the NFS share's size isn't enforced
  accessModes:
    - ReadWriteMany
  nfs:
    server: nasaurus
    path: /volume1/NAS/downloads
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
