apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  template:
    metadata:
      labels:
        app: gogs
        # istio-injection: enabled
        version: v1
    spec:
      containers:
      - name: gogs
        image: gogs/gogs:0.13.2
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: SOCAT_LINK
          value: "false"
        - name: DISABLE_REGISTRATION
          value: "true"
        volumeMounts:
        - name: gogs-persistent-storage
          mountPath: /data
      volumes:
      - name: gogs-persistent-storage
        persistentVolumeClaim:
          claimName: gogs-pv-claim
