apiVersion: v1
kind: Service
metadata:
  name: gogs-svc
spec:
  type: ClusterIP
  selector:
    app: gogs
  ports:
  - name: ssh
    protocol: TCP
    port: 10022
    targetPort: 22
  - name: http
    protocol: TCP
    port: 18080
    targetPort: 3000