jellyfin:
  persistence:
    config:
      enabled: true
      size: 500Mi
    movies:
        enabled: true
        mountPath: /movies
        type: pvc
        existingClaim: movie-pvc
    shows:
        enabled: true
        mountPath: /shows
        type: pvc
        existingClaim: shows-pvc