jellyfin:
  persistence:
    config:
      enabled: true
      size: 2Gi
    movies:
        enabled: true
        mountPath: /movies
        type: pvc
        existingClaim: movie-pvc
    shows:
        enabled: true
        mountPath: /shows
        type: pvc
        existingClaim: shows-pvc