jellyfin:
  persistence:
    config:
      enabled: true
      size: 8Gi
      accessMode: ReadWriteOnce
    movies:
        enabled: true
        mountPath: /movies
        existingClaim: movie-pvc
    shows:
        enabled: true
        mountPath: /shows
        existingClaim: shows-pvc