sonarr:
  persistence:
    storageClass: ""
    existingClaim: ""
    enabled: true
    accessMode: ReadWriteOnce
    size: 800Mi
    # -- if you need any additional volumes, you can define them here
    additionalVolumes: []
    # -- if you need any additional volume mounts, you can define them here
    additionalMounts: 
      - name: shows
        mountPath: /shows
        type: pvc
        existingClaim: shows-pvc
